2025-01-29 00:18:27,702 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MyOwnProjects\HomeworkUrban\Module_12\tests_12_4.py", line 24, in test_run
    obj = Runner(14, 5)
          ^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\MyOwnProjects\HomeworkUrban\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-29 00:18:27,704 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MyOwnProjects\HomeworkUrban\Module_12\tests_12_4.py", line 12, in test_walk
    obj = Runner('First', -5)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\MyOwnProjects\HomeworkUrban\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
